
// =====================================================
// Localization
// =====================================================

window.LOCALES = {
    uk: {
        appTitle: 'Гладіаторський RPG-симулятор',
        newGame: 'Нова гра',
        continueGame: 'Продовжити',
        startNewGame: 'Нова гра',
        resetProgress: 'Скинути прогрес',
        settings: 'Налаштування',
        options: 'Опції',
        achievements: 'Досягнення',
        stats: 'Статистика',
        playerSheet: 'Показники героя',
        characteristics: 'Характеристики',
        damage: 'Урон',
        defense: 'Захист',
        critChance: 'Шанс криту',
        dodgeChance: 'Шанс ухилення',
        attackBonus: 'Бонус атаки',
        defenseBonus: 'Бонус захисту',
        equipmentStats: 'Екіпірування',
        pointsAvailable: 'Доступні очки',
        quests: 'Квести',
        leaderboard: 'Лідери',
        start: 'Почати',
        back: 'Назад',
        close: 'Закрити',
        save: 'Зберегти',
        apply: 'Застосувати',
        defaults: 'Налаштування за замовченням',
        language: 'Мова',
        gradient: 'Градієнт фону',
        backgroundColor: 'Колір фону',
        textColor: 'Колір тексту',
        showEnemyPreview: 'Показувати характеристики ворога',
        showBossPreview: 'Показувати характеристики боса',
        menu: 'Меню',
        arena: 'Арена',
        bossArena: 'Арена босів',
        shop: 'Магазин',
        equipmentShop: 'Екіпіровка',
        potionShop: 'Зілля',
        sleep: 'Спати',
        usePotion: 'Зілля',
        progression: 'Прокачка',
        attack: 'Атакувати',
        specialAttack: 'Спецатака',
        flee: 'Відступити',
        fight: 'Битися',
        continueBattle: 'Продовжити бій',
        fightNow: 'Бій!',
        inspect: 'Оглянути',
        sell: 'Продати',
        shareRecord: 'Поділитися рекордом',
        continueEndless: 'Продовжити нескінченний режим',
        endlessMode: 'Нескінченний режим',
        questJournal: 'Журнал квестів',
        questObjective: 'Мета',
        questLore: 'Лор',
        questReward: 'Нагорода',
        questDialogue: 'Діалог',
        resumeDialogue: 'Продовжити діалог',
        actionLog: 'Журнал дій',
        hotkeys: 'Гарячі клавіші',
        holdCtrlForHotkeys: 'Затисни Ctrl, щоб побачити підказки. Клавіші працюють і без Ctrl.',
        day: 'День',
        level: 'Рівень',
        xp: 'Досвід',
        health: 'Здоров\'я',
        mana: 'Мана',
        gold: 'Золото',
        strength: 'Сила',
        dexterity: 'Спритність',
        intelligence: 'Інтелект',
        skillPoints: 'Очки навичок',
        attributePoints: 'Очки характеристик',
        wins: 'Перемоги',
        losses: 'Поразки',
        hits: 'Удари',
        potionsUsed: 'Використано зіль',
        bossWins: 'Перемоги над босами',
        currentEnemy: 'Поточний ворог',
        currentBoss: 'Поточний бос',
        noSave: 'Збереження не знайдено',
        overwriteSave: 'Поточний прогрес буде втрачено. Почати нову гру?',
        journalTitle: 'Журнал дій',
        journalEmpty: 'Поки що немає дій.',
        newLevel: 'Новий рівень!',
        levelPoints: 'Очки можна розподілити пізніше',
        chooseUpgrade: 'Оберіть, що покращити',
        inventoryValue: 'Вартість інвентарю',
        score: 'Рахунок',
        leaderboardHint: 'Офлайн заготовка для майбутнього онлайн-рейтингу',
        buy: 'Купити',
        used: 'Використано',
        notEnoughGold: 'Недостатньо золота',
        noPotions: 'Немає зіль',
        nothingToSell: 'Немає що продавати',
        notEnoughMana: 'Недостатньо мани',
        achievementsUnlocked: 'Досягнення',
        questsUnlocked: 'Квести',
        settingsSaved: 'Налаштування збережено',
        settingsReset: 'Налаштування скинуто',
        progressReset: 'Прогрес скинуто',
        gameStarted: 'Гру розпочато',
        loadedSave: 'Збереження завантажено',
        noEnemyPreview: 'Характеристики приховано',
        enemyPreview: 'Характеристики ворога',
        bossPreview: 'Характеристики боса',
        sleepEvent: 'Подія сну',
        story: 'Історія',
        storyIntro: 'Ти виходиш на арену, де честь, кров і золото вирішують долю гладіатора.',
        openQuests: 'Відкрити квести',
        openLeaderboard: 'Відкрити лідери',
        openStats: 'Відкрити статистику',
        openAchievements: 'Відкрити досягнення',
        openSettings: 'Відкрити налаштування',
        needPoints: 'Немає очок',
        bought: 'Куплено',
        sold: 'Продано',
        equipped: 'Екіпіровано',
        rest: 'Відпочинок',
        romanPatron: 'Заможний римлянин',
        romanJoined: 'Заможний римлянин всиновив тебе та відкрив власну школу тренувань.',
        romanSleepBonus: 'Тепер сон відновлює більше здоров\'я та мани.',
        romanTrainingBonus: 'Тренування з іншими бійцями дає більше досвіду.',
        endlessUnlocked: 'Відкрито нескінченний режим',
        recordShared: 'Рекорд готово до поширення',
        battleWon: 'Перемога',
        battleLost: 'Поразка',
        criticalHit: 'Критичний удар',
        dodge: 'Ухилення',
        shieldBreak: 'Щит зламано',
        poison: 'Отруєння',
        manaDrained: 'Мана виснажена',
        questComplete: 'Квест виконано',
        achievementComplete: 'Досягнення виконано',
        eventGood: 'Добра подія',
        eventBad: 'Невдала подія',
        eventNeutral: 'Нейтральна подія',
		refreshOpponent: 'Оновити суперника',
		account: 'Акаунт'
    },
    en: {
        appTitle: 'Gladiator RPG Simulator',
        newGame: 'New Game',
        continueGame: 'Continue',
        startNewGame: 'New Game',
        resetProgress: 'Reset Progress',
        settings: 'Settings',
        options: 'Options',
        achievements: 'Achievements',
        stats: 'Statistics',
        playerSheet: 'Hero sheet',
        characteristics: 'Characteristics',
        damage: 'Damage',
        defense: 'Defense',
        critChance: 'Crit chance',
        dodgeChance: 'Dodge chance',
        attackBonus: 'Attack bonus',
        defenseBonus: 'Defense bonus',
        equipmentStats: 'Equipment',
        pointsAvailable: 'Points available',
        quests: 'Quests',
        leaderboard: 'Leaderboard',
        start: 'Start',
        back: 'Back',
        close: 'Close',
        save: 'Save',
        apply: 'Apply',
        defaults: 'Default settings',
        language: 'Language',
        gradient: 'Background gradient',
        backgroundColor: 'Background color',
        textColor: 'Text color',
        showEnemyPreview: 'Show enemy stats',
        showBossPreview: 'Show boss stats',
        menu: 'Menu',
        arena: 'Arena',
        bossArena: 'Boss Arena',
        shop: 'Shop',
        equipmentShop: 'Equipment',
        potionShop: 'Potions',
        sleep: 'Sleep',
        usePotion: 'Potion',
        progression: 'Progression',
        attack: 'Attack',
        specialAttack: 'Special Attack',
        flee: 'Retreat',
        fight: 'Fight',
        continueBattle: 'Continue battle',
        fightNow: 'Fight!',
        inspect: 'Inspect',
        sell: 'Sell',
        shareRecord: 'Share record',
        continueEndless: 'Continue endless mode',
        endlessMode: 'Endless mode',
        questJournal: 'Quest journal',
        questObjective: 'Objective',
        questLore: 'Lore',
        questReward: 'Reward',
        questDialogue: 'Dialogue',
        resumeDialogue: 'Resume dialogue',
        actionLog: 'Action log',
        hotkeys: 'Hotkeys',
        holdCtrlForHotkeys: 'Hold Ctrl to see shortcuts.',
        day: 'Day',
        level: 'Level',
        xp: 'Experience',
        health: 'Health',
        mana: 'Mana',
        gold: 'Gold',
        strength: 'Strength',
        dexterity: 'Dexterity',
        intelligence: 'Intelligence',
        skillPoints: 'Skill points',
        attributePoints: 'Attribute points',
        wins: 'Wins',
        losses: 'Losses',
        hits: 'Hits',
        potionsUsed: 'Potions used',
        bossWins: 'Boss wins',
        currentEnemy: 'Current enemy',
        currentBoss: 'Current boss',
        noSave: 'No save found',
        overwriteSave: 'Current progress will be lost. Start a new game?',
        journalTitle: 'Action log',
        journalEmpty: 'No actions yet.',
        newLevel: 'New level!',
        levelPoints: 'Points can be spent later',
        chooseUpgrade: 'Choose what to improve',
        inventoryValue: 'Inventory value',
        score: 'Score',
        leaderboardHint: 'Offline draft for future online ranking',
        buy: 'Buy',
        used: 'Used',
        notEnoughGold: 'Not enough gold',
        noPotions: 'No potions',
        nothingToSell: 'Nothing to sell',
        notEnoughMana: 'Not enough mana',
        achievementsUnlocked: 'Achievements',
        questsUnlocked: 'Quests',
        settingsSaved: 'Settings saved',
        settingsReset: 'Settings reset',
        progressReset: 'Progress reset',
        gameStarted: 'Game started',
        loadedSave: 'Save loaded',
        noEnemyPreview: 'Stats hidden',
        enemyPreview: 'Enemy stats',
        bossPreview: 'Boss stats',
        sleepEvent: 'Sleep event',
        story: 'Story',
        storyIntro: 'You step into the arena where honor, blood and gold decide a gladiator’s fate.',
        openQuests: 'Open quests',
        openLeaderboard: 'Open leaderboard',
        openStats: 'Open statistics',
        openAchievements: 'Open achievements',
        openSettings: 'Open settings',
        needPoints: 'No points available',
        bought: 'Bought',
        sold: 'Sold',
        equipped: 'Equipped',
        rest: 'Rest',
        romanPatron: 'Wealthy Roman',
        romanJoined: 'A wealthy Roman adopted you and opened his private training school.',
        romanSleepBonus: 'Sleep now restores more health and mana.',
        romanTrainingBonus: 'Training with other fighters grants more experience.',
        endlessUnlocked: 'Endless mode unlocked',
        recordShared: 'Record prepared for sharing',
        battleWon: 'Victory',
        battleLost: 'Defeat',
        criticalHit: 'Critical hit',
        dodge: 'Dodge',
        shieldBreak: 'Shield broken',
        poison: 'Poisoned',
        manaDrained: 'Mana drained',
        questComplete: 'Quest completed',
        achievementComplete: 'Achievement completed',
        eventGood: 'Good event',
        eventBad: 'Bad event',
        eventNeutral: 'Neutral event',
		refreshOpponent: 'refresh Opponent',
		account: 'Account'
    }
};

window.i18n = {
    t(key, vars = {}) {
        const lang = window.gameSettings?.language || window.DEFAULT_SETTINGS.language;
        const bundle = window.LOCALES[lang] || window.LOCALES.uk;
        const fallback = window.LOCALES.uk;
        const raw = key.split('.').reduce((obj, part) => obj && obj[part], bundle)
            ?? key.split('.').reduce((obj, part) => obj && obj[part], fallback)
            ?? key;
        return String(raw).replace(/\{\{(\w+)\}\}/g, (_, k) => vars[k] ?? '');
    }
};

window.T = (key, vars = {}) => window.i18n.t(key, vars);

window.Text = {
    red: (html) => `<span class="text-red">${html}</span>`,
    blue: (html) => `<span class="text-blue">${html}</span>`,
    green: (html) => `<span class="text-green">${html}</span>`,
    gold: (html) => `<span class="text-gold">${html}</span>`,
    gray: (html) => `<span class="text-gray">${html}</span>`,
    bold: (html) => `<strong>${html}</strong>`,
    italic: (html) => `<em>${html}</em>`
};
